apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-player
  namespace: mozart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-player
      version: v1
  template:
    metadata:
      labels:
        app: events-player
        version: v1
    spec:
      containers:
      - name: events-player
        image: ccie-gitlab.ccie.cisco.com:4567/mozart/infrastructure/eventing/cloudevent-player:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: api_default_generator_gateways
          value: '{"urls": ["http://localhost/events/pub", "http://k.ccie.cisco.com:32051/events/pub", "http://sj-k.ccie.cisco.com:32051/events/pub", "http://aws-k.ccie.cisco.com:32051/events/pub", "https://events-player.k.ccie.cisco.com/events/pub", "https://events-player.sj-k.ccie.cisco.com/events/pub", "https://events-player.aws-k.certs.cloud/events/pub", "https://ccie360-events.k.ccie.cisco.com/events/pub", "https://lds-events.k.ccie.cisco.com/events/pub"]}'
        - name: api_browser_queue_size
          value: "1500"
        - name: api_tag
          value: "0.1.14"
        - name: api_default_generator_event
          value: '{"event_source": "https://dummy-source.ccie.cisco.com", "event_type":"com.cisco.certs.dummy.test.requested.v1"}'
